#!/bin/bash

# This script is used to install all the necessary dependencies necessary
# to run a digole 2 inch lcd alongside svxlink for a real time display of
# svxlink status.

# SCRIPT CONTRIBUTORS:
# Aaron Crawford (N3MBH), Dan Loranger (KG7PAR)
# Updates by Keith Tweed (VA6MPL)

# Check if the user is root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

#Install the needed support applications

apt-get install python3-smbus python3-pigpio python3-pip python3-rpi.gpio rpi.gpio-common python3-inotify

# Enable pigpio daemon
systemctl enable pigpiod

# apt-get install python3-smbus python3-pigpio  python-pip
# pip3 install inotify

# mak the LCD service executable
 chmod +x LCD

#move the python script into the expected location, make it executable
 cp PI-REPEATER-8X-LCD.py /usr/local/bin/PI-REPEATER-8X-LCD.py
sleep 1
 chmod +x /usr/local/bin/PI-REPEATER-8X-LCD.py

#move the LCD file to have it run automatically at boot
mv ./LCD /etc/init.d/
cd /etc/init.d
update-rc.d LCD defaults

